apiVersion: ops.signalops.io/v1alpha1
kind: RemediationPlan
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: remediationplan-sample
spec:
  # TODO(user): Add fields here
